---
- name: Configure MacBook Pro Ubuntu Desktop homelab node
  # TODO: Can this use `hosts: all` and `connection: all` so that testing infrastructure with Molecule can be simplified (i.e. no need for separate ci/default `converge.yml` and can reintegrate `tasks/main.yml` into this main playbook)?
  hosts: localhost
  connection: local
  become: false

  vars:
    homelab_user: ubuntu # Match the username that was created during the Ubuntu installation

  tasks:
    - name: Run main configuration tasks
      ansible.builtin.import_tasks: tasks/main.yml
