---
- name: Configure MacBook Pro Ubuntu Desktop homelab node
  hosts: localhost
  connection: local
  become: false

  vars:
    homelab_user: ubuntu # Match the username that was created during the Ubuntu installation

  tasks:
    - name: Run main configuration tasks
      ansible.builtin.import_tasks: tasks/main.yml
